language: node_js
node_js:
  - "8"
dist: trusty
env:
  - NODE_ENV=production
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run heroku-postbuild
script:
  - nohup npm run lt &
  - nohup npm run start &
  - sleep 5
  - npm run test
