language: node_js
node_js:
  - "8"
dist: trusty
sudo: false
addons:
  chrome: stable
env:
  - NODE_ENV=production
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install
  - npm install --prefix client
  - npm run heroku-postbuild
script:
  - nohup npm run start &
  - sleep 10
  - npm run test
