language: node_js
node_js:
  - "8"
dist: trusty
sudo: false
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run dev
  - npm run test
