# language: node_js
# node_js:
#   - "8"
# dist: trusty
# env:
#   - NODE_ENV=production
# cache:
#   directories:
#     - node_modules
#     - client/node_modules
# install:
#   - npm install
#   - npm run heroku-postbuild
# script:
#   - nohup npm run lt &
#   - nohup npm run start &
#   - sleep 3
#   - npm run test:travis

language: node_js
node_js:
  - "8"
dist: trusty
sudo: required
addons:
  chrome: stable
env:
  - NODE_ENV=production
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run heroku-postbuild
before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
  - nohup npm run lt &
  - nohup google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - nohup npm run start &
  - sleep 3
  - npm run test
